task:
  freebsd_instance:
    cpu: 1
    matrix:
      - image_family: freebsd-15-0-snap
      - image_family: freebsd-14-0
      - image_family: freebsd-13-3
  install_script: pkg install -y bash git autoconf automake libtool groff pkgconf
  build_script:
    - ./Configure -n freebsd
    - make
  test_script:
    - bash ./check.bash freebsd
  autotools_build_script:
    - git clean -fdx .
    - autoreconf -vif
    - ./configure
    - make
    - make install
  autotools_test_script:
    - make check
    - cat test-suite.log
    - make distcheck
